name: One-Off Deploy via SST to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "public/**"
      - "prisma/**"
      - ".github/**"
      - "package.json"
      - "sst.config.ts"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Cache Next.js Build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache/
            .open-next/
            .sst/
          key: cache-${{ hashFiles('**.[jt]s', '**.[jt]xs') }}

      - name: Install projects deps
        run: npm install

      - name: Install AWS Creds
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Deploy to AWS with SST
        run: npx sst deploy --stage prod

      - name: Clean Up AWS Profile
        run: |
          rm -rf ~/.aws
